const words = [
  { word: "latitude", hint: "Geographical term" },
  { word: "escalator", hint: "Moving staircase" },
  { word: "barricade", hint: "Obstacle or barrier" },
  { word: "chameleon", hint: "Color-changing reptile" },
  { word: "algorithm", hint: "Set of rules in computing" },
  { word: "jubilant", hint: "Feeling of great happiness" },
  { word: "quarantine", hint: "Isolation to prevent disease spread" },
  { word: "volunteer", hint: "One who offers service freely" },
  { word: "yacht", hint: "Luxury watercraft" },
  { word: "zoology", hint: "Study of animals" },
  { word: "wholesale", hint: "Selling goods in large quantities" },
  { word: "ventilate", hint: "Admit fresh air" },
  { word: "umbrella", hint: "Rain protection" },
  { word: "therapist", hint: "Treatment professional" },
  { word: "souvenir", hint: "Travel keepsake" },
  { word: "republic", hint: "Form of government" },
  { word: "quicksand", hint: "Treacherous sinking sand" },
  { word: "publisher", hint: "Book or magazine producer" },
  { word: "ornament", hint: "Decoration" },
  { word: "navigator", hint: "One who directs the route" },
  { word: "migraine", hint: "Severe headache" },
  { word: "labyrinth", hint: "Complex maze" },
  { word: "kaleidoscope", hint: "Tube of mirrors with colored objects" },
  { word: "juxtapose", hint: "To place side by side" },
  { word: "insomnia", hint: "Inability to sleep" },
  { word: "hibernate", hint: "Long-term torpor in animals" },
  { word: "glacier", hint: "Slow-moving mass of ice" },
  { word: "flamboyant", hint: "Strikingly bold or brilliant" },
  { word: "ecosystem", hint: "Biological community interaction" },
  { word: "dynamite", hint: "Explosive material" },
  { word: "donut", hint: "Very sweet and tasty food" },
  { word: "piano", hint: "Musical instrument with keys" },
];

export { words };
